version: "3"

services:
  db:
    image: postgres
    hostname: db
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: postgres-dev
      POSTGRES_PASSWORD: s3cr3tp4ssw0rd
    ports:
      - 5432:5432
    restart: always
  app:
    image: recorder
    volumes:
      - ./data/:/data/
    working_dir: /go/src/
    ports:
      - 9299:9299
    env_file:
      - ./.env
    depends_on:
      - db
    links:
      - db
    command: ["go", "run", "main.go"]
